# Generated by Django 2.0.1 on 2018-01-13 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edc_base', '0002_auto_20171031_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='clinic_label_printer',
            field=models.CharField(blank=True, help_text='Change in Administration:Edc Label', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='lab_label_printer',
            field=models.CharField(blank=True, help_text='Change in Administration:Edc Label', max_length=100, null=True),
        ),
    ]
