# Generated by Django 2.0.1 on 2018-01-14 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edc_base', '0003_auto_20180113_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='clinic_label_printer',
            field=models.CharField(blank=True, help_text='Change in <a href="/edc_label/">Edc Label Administration</a>', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='lab_label_printer',
            field=models.CharField(blank=True, help_text='Change in <a href="/edc_label/">Edc Label Administration</a>', max_length=100, null=True),
        ),
    ]
